### ISSUE TITLE
Switch to default pep8 code style for python

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisCummins/ProGraML#100]
At the moment, python code uses an approximation of the Google Python style guide, specifically, 2-space indentation and PascalCase method names. In the interest of being more "python-y", I would like to revert to a regular [PEP 8](https://www.python.org/dev/peps/pep-0008/) format. This can be broken down into subtasks:

- [x] Use 4 spaces for indentation rather than 2.
- [x] Update the [format](https://github.com/ChrisCummins/format) tool to use the regular, unmodified black code formatter for python.
- [x] Replace `PascalCase` function names with `lower_snake_case`.

**Comment by Zacharias030** [comment]
Let me suggest black -l 120 :)
It saves so much space on each page and the stuff crossing 100 columns under black formatting are usually just strings and function calls with keywords.
Am 22. Aug. 2020, 00:18 +0200 schrieb Chris Cummins <notifications@github.com>:

**Comment by ChrisCummins** [comment]
120! I'm personally struggling to come to terms with anything about -l 80 :D

**Comment by ChrisCummins** [comment]
As of v0.3.0 the public API is now all pep8-formatted.
