### ISSUE TITLE
Re-implement LSTM in PyTorch

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisCummins/ProGraML#124]
TensorFlow is a heavy dependency, and only the LSTM baseline uses it

**Comment by anon767** [comment]
FWIW, I think it could be worth the effort to reimplement the GGNN in Pytorch Geometric. As it would shift a lot logic out of PrograML.

**Comment by ChrisCummins** [comment]
@anon767 Great idea, I would love this. The core ProGraML implementation is actually quite small, but there's a lot of work in custom data loaders, batchers, etc that could be delegated to another library.

Unfortunately I really don't have much bandwidth to work on this project right now, but contributions very welcome!.

Cheers,
Chris

**Comment by ChrisCummins** [comment]
Superseded by #178.
