### ISSUE TITLE
The code scripts for the original dataset preprocessing

### ISSUE THREAD

**Issue by QiuJYWX** [ChrisCummins/ProGraML#132]
Hi ProGraML,

Thanks for your sharing of your excellent work ProGraML! Your have provide the link for the Dataflow Dataset, including a wide range of projects, labels for several compiler data flows, and logs for the published experimental results. 
I am now trying to apply your method to my own dataset. Would you please provide the code scripts for the original dataset preprocessing? For example, the scripts converting the source code to the LLVM IR, the scripts generating the labels. If you can share these code scripts, that would be highly appreciated.

**Comment by ChrisCummins** [comment]
Hi there, to generate LLVM-IR from source code, you can use `clang -emit-llvm` (for C/C++ code). Other tools have similar flags, e.g. `swiftc -emit-ir` for Swift. E.g.

```
$ clang -emit-llvm -S foo.c -o foo.ll
```

Once you have the `.ll` files of LLVM-IR, use [llvm2graph](https://github.com/ChrisCummins/ProGraML/blob/development/programl/Documentation/cmd/llvm2graph.txt) to produce the graph. E.g.

```
$ bazel run -c opt //programl/cmd:llvm2graph < foo.ll > foo.pbtxt
```

After that, you can load the [ProgramGraph protocol buffer](https://github.com/ChrisCummins/ProGraML/blob/development/programl/proto/program_graph.proto#L39-L45) and create your own labels however you want. For example, for the CPU/GPU devmap dataset, I [add a graph-level feature](https://github.com/ChrisCummins/ProGraML/blob/development/programl/task/devmap/dataset/create.py#L136-L137) "devmap_label" to represent the desired target label.

Hope that helps. Let me know how you get on.

Cheers,
Chris

**Comment by QiuJYWX** [comment]
> Hi there, to generate LLVM-IR from source code, you can use `clang -emit-llvm` (for C/C++ code). Other tools have similar flags, e.g. `swiftc -emit-ir` for Swift. E.g.
> 
> ```
> $ clang -emit-llvm -S foo.c -o foo.ll
> ```
> 
> Once you have the `.ll` files of LLVM-IR, use [llvm2graph](https://github.com/ChrisCummins/ProGraML/blob/development/programl/Documentation/cmd/llvm2graph.txt) to produce the graph. E.g.
> 
> ```
> $ bazel run -c opt //programl/cmd:llvm2graph < foo.ll > foo.pbtxt
> ```
> 
> After that, you can load the [ProgramGraph protocol buffer](https://github.com/ChrisCummins/ProGraML/blob/development/programl/proto/program_graph.proto#L39-L45) and create your own labels however you want. For example, for the CPU/GPU devmap dataset, I [add a graph-level feature](https://github.com/ChrisCummins/ProGraML/blob/development/programl/task/devmap/dataset/create.py#L136-L137) "devmap_label" to represent the desired target label.
> 
> Hope that helps. Let me know how you get on.
> 
> Cheers,
> Chris


Hi Chris,

Thanks for your kindly reply. I will process my dataset according to your suggestions. 
BTW, is it possible to provide a detailed guidance doc introducing the pipline of proGraML? e.g., the process from source code to LLVM IR, IR to different flow graphs, final inputs to DL model, model training and testing.  

Kind regards,
QIUJY

**Comment by ChrisCummins** [comment]
Hi Qiujy,

> is it possible to provide a detailed guidance doc introducing the pipline of proGraML? e.g., the process from source code to LLVM IR, IR to different flow graphs, final inputs to DL model, model training and testing.

Yes, this is a great suggestion. I will work on adding a document describing the processing pipeline as part of #88. In the mean time, please check out the description [the paper](https://arxiv.org/pdf/2003.10536.pdf)!

Cheers,
Chris
