### ISSUE TITLE
link error when running on aws EC2

### ISSUE THREAD

**Issue by shmsong** [ChrisCummins/ProGraML#134]
**Failure observed with an EC2 x86 instance with [ubuntu deep learning AMI](https://aws.amazon.com/marketplace/pp/Amazon-Web-Services-AWS-Deep-Learning-AMI-Ubuntu-1/B07Y43P7X5):**

**Repro: (after installation)**

`$ clang2graph fib.c `
_clang2graph: error while loading shared libraries: libLLVMPolly.so: cannot open shared object file: No such file or directory_

`$ llvm2graph fib.ll`
_llvm2graph: error while loading shared libraries: libLLVMPolly.so: cannot open shared object file: No such file or directory_

**Workaround**
Found simple work around with:
`$ cp $HOME/.local/opt/programl/lib && cp LLVMPolly.so libLLVMPolly.so`
apparently either the naming of the shared lib (that'd go inside LLVM) or the linking needed to be updated to fix this properly.

**Comment by ChrisCummins** [comment]
Hi @shmsong, thanks for posting this issue and the fix! I've added your workaround as a step in the install script.

Cheers,
Chris

**Comment by ChrisCummins** [comment]
Merged your workaround in #135, but I'll keep this issue open a while since I haven't been able to test on EC2.

Cheers,
Chris

**Comment by ChrisCummins** [comment]
Closing this now, but please re-open if the issue persists on EC2!

Cheers,
Chris
