### ISSUE TITLE
bazel issues

### ISSUE THREAD

**Issue by QiuJYWX** [ChrisCummins/ProGraML#137]
Hi Chris,

Thanks for your time and attention. I am trying to install this repo, the following error occurred, would you please provide me some advice or help?

qjy@ubuntu:~$ cd ProGraML/
qjy@ubuntu:~/ProGraML$ bazel test //programl/...

.......
ERROR: Failed to load Skylark extension '@programl//tools:bzl/deps.bzl'.
It usually happens when the repository is not defined prior to being used.
Maybe repository 'programl' was defined later in your WORKSPACE file?
ERROR: Skipping '//programl/...': cycles detected during target parsing.
ERROR: Skipping '//programl/...': cycles detected during target parsing.
WARNING: Target pattern parsing failed. Continuing anyway.
ERROR: Failed to load //external package: error loading package 'external': Cycle encountered while loading package external.
INFO: Elapsed time: 0.416s
ERROR: Couldn't start the build. Unable to run tests.**_

**Comment by ChrisCummins** [comment]
Hi @QiuJYWX, thanks for the bug report. I'm out of the office at the moment but I'll try to reproduce and get back to you on Tuesday.

Cheers,
Chris

**Comment by QiuJYWX** [comment]
Hi Chris,
Thanks for your reply. I have solved the above issue by update the bazel to the latest version. However, although I have installed all the required packages manually, there occurs another error:

qjy@ubuntu:~/ProGraML$ bazel test //programl/...
Starting local Bazel server and connecting to it...
INFO: Repository programl_requirements instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule pip_import defined at:
  /home/qjy/.cache/bazel/_bazel_qjy/d9f1e0ab2452a26be82cda9c3e122c2b/external/rules_python/python/pip.bzl:51:29: in <toplevel>
ERROR: An error occurred during the fetch of repository 'programl_requirements':
   Traceback (most recent call last):
	File "/home/qjy/.cache/bazel/_bazel_qjy/d9f1e0ab2452a26be82cda9c3e122c2b/external/rules_python/python/pip.bzl", line 49, column 13, in _pip_import_impl
		fail("pip_import failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: pip_import failed:  (Timed out)
ERROR: no such package '@programl_requirements//': pip_import failed:  (Timed out)
INFO: Elapsed time: 3602.177s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded

**Comment by ChrisCummins** [comment]
Hi @QiuJYWX, thanks for the follow up and apologies for my delayed response. The error that you are seeing is caused by `pip` taking longer than 1 hour to download the dependent packages. Do you have an unstable/slow internet connection? You could try allowing a longer timeout by changing [this line](https://github.com/ChrisCummins/ProGraML/blob/development/WORKSPACE#L39) to something like `timeout = 7200,` (2 hours).

Cheers,
Chris

**Comment by QiuJYWX** [comment]
Hi Chris,

Thanks for your suggestion. I have revised the timeout = 7200. However, the following error occurred:

qjy@ubuntu:~/ProGraML$ bazel test //programl/...
INFO: Call stack for the definition of repository 'org_tensorflow' which is a http_archive (rule definition at /home/qjy/.cache/bazel/_bazel_qjy/d9f1e0ab2452a26be82cda9c3e122c2b/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/qjy/.cache/bazel/_bazel_qjy/d9f1e0ab2452a26be82cda9c3e122c2b/external/programl/tools/bzl/deps.bzl:159:3
 - /home/qjy/ProGraML/WORKSPACE:6:1
WARNING: Download from https://github.com/ChrisCummins/tensorflow/archive/f13f807c83c0d8d4d1ef290a17f26fe884ccfe2f.tar.gz failed: class java.io.IOException Tried to reconnect at offset 7,485,186 but server didn't support it
ERROR: An error occurred during the fetch of repository 'org_tensorflow':
   java.io.IOException: Error downloading [https://github.com/ChrisCummins/tensorflow/archive/f13f807c83c0d8d4d1ef290a17f26fe884ccfe2f.tar.gz] to /home/qjy/.cache/bazel/_bazel_qjy/d9f1e0ab2452a26be82cda9c3e122c2b/external/org_tensorflow/f13f807c83c0d8d4d1ef290a17f26fe884ccfe2f.tar.gz: Tried to reconnect at offset 7,485,186 but server didn't support it
ERROR: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://github.com/ChrisCummins/tensorflow/archive/f13f807c83c0d8d4d1ef290a17f26fe884ccfe2f.tar.gz] to /home/qjy/.cache/bazel/_bazel_qjy/d9f1e0ab2452a26be82cda9c3e122c2b/external/org_tensorflow/f13f807c83c0d8d4d1ef290a17f26fe884ccfe2f.tar.gz: Tried to reconnect at offset 7,485,186 but server didn't support it
ERROR: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://github.com/ChrisCummins/tensorflow/archive/f13f807c83c0d8d4d1ef290a17f26fe884ccfe2f.tar.gz] to /home/qjy/.cache/bazel/_bazel_qjy/d9f1e0ab2452a26be82cda9c3e122c2b/external/org_tensorflow/f13f807c83c0d8d4d1ef290a17f26fe884ccfe2f.tar.gz: Tried to reconnect at offset 7,485,186 but server didn't support it
INFO: Elapsed time: 906.144s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

Would you hele me figure out the solution? BTW, I can download the 'https://github.com/ChrisCummins/tensorflow/archive/f13f807c83c0d8d4d1ef290a17f26fe884ccfe2f.tar.gz' using the browser successfully.

Thanks again.

**Comment by ChrisCummins** [comment]
Hi @QiuJYWX, again, this is a network connectivity issue. I'm guessing that your internet connection is either slow/unreliable.

Still, I'm sorry that you've been having these problems and let's try and get your build working! Since the error is caused by bazel being unable to completely download a file, have you tried downloading the file to the expected place yourself?

```sh
$ rm -f /home/qjy/.cache/bazel/_bazel_qjy/d9f1e0ab2452a26be82cda9c3e122c2b/external/org_tensorflow/f13f807c83c0d8d4d1ef290a17f26fe884ccfe2f.tar.gz && wget https://github.com/ChrisCummins/tensorflow/archive/f13f807c83c0d8d4d1ef290a17f26fe884ccfe2f.tar.gz -O /home/qjy/.cache/bazel/_bazel_qjy/d9f1e0ab2452a26be82cda9c3e122c2b/external/org_tensorflow/f13f807c83c0d8d4d1ef290a17f26fe884ccfe2f.tar.gz
```

Cheers,
Chris

**Comment by ChrisCummins** [comment]
In #142 I made some changes to minimize the chance of this issue recurring:

* reduced the size of the third-party dependency footprint
* split the core library dependencies from the task-specific dependencies

This should ease the burden on the network, though please re-open if the issue persists!

Cheers,
Chris
