### ISSUE TITLE
Issues with running clang2graph and graph2dot

### ISSUE THREAD

**Issue by akash-isu** [ChrisCummins/ProGraML#145]
When I run the following command, I end up getting this error.

clang clang2graph -O3 fib.c | graph2dot

/usr/bin/ld: clang2graph: _ZTIh: invalid version 18 (max 0)
/usr/bin/ld: clang2graph: error adding symbols: bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
graph2dot: command not found

**Comment by akash-isu** [comment]
Not facing the same issue anymore. Was probably an issue with multiple installations of clang on my system.

**Comment by ChrisCummins** [comment]
Glad to hear you were able to resolve this. If the issue reoccurs I would be interested in gather more details to reproduce this so that I can figure out a fix.

Cheers,
Chris
