### ISSUE TITLE
Building and running projects from the dataset

### ISSUE THREAD

**Issue by ygambhir** [ChrisCummins/ProGraML#150]
Hello, my student group and I are interested in using a subset of this dataset to predict optimal loop unrolling factors. This would require us to run each project, but we realized that each file is part of multi-source projects and we can't find an explicit linkage between files to run them. 

Is it at all possible to access the dataset on a project level instead of file level such that the programs can be run? Any advice or guidance would be greatly appreciated!

**Comment by ChrisCummins** [comment]
Hi @ygambhir, apologies for the slow response, I was on my honeymoon :) The [DeepDataFlow](https://github.com/ChrisCummins/ProGraML/blob/development/Documentation/DataflowDataset.md#dataflow-dataset) isn't well suited for your needs, as it contains only static source code, not the driver scripts or inputs that are required to run the programs. What you could do is use an executable benchmark suite and derive ProGraML representations for those programs. Let me know if that helps.

Cheers,
Chris
