### ISSUE TITLE
Is it possible to debug and explore the models without Bazel?

### ISSUE THREAD

**Issue by wanyao1992** [ChrisCummins/ProGraML#153]
Hi Chris,

Thanks for your open source of this nice project and I am very interested in this project.
Recently, I have successfully deployed this project after some efforts since I am not familiar with the Bazel build tool. So I am wondering whether I can run and explore the integrated graph models via Python command line or directly debug the model through PyCharm.
Actually, I have run the `tasks/dataflow/train_ggnn.py` in PyCharm, and it returns that many packages are not found such as `ImportError: cannot import name 'program_graph_pb2'`.

It will be highly appreciated that if you can give me some suggestion on how to debug and explore the models.

Thanks.

**Comment by ChrisCummins** [comment]
Hi @wanyao1992, so sorry for the delayed response! I must have missed the notification for this.

Yes you cannot run the code in-place as there are compiled dependencies that will be missing (like the `program_graph_pb2` package you reference). However you *can* use bazel to build the full codebase and then run that.

If you run:

```sh
$ bazel build -c opt //tasks/dataflow:train_ggnn
```

That will generate a file `bazel-bin/tasks/dataflow/train_ggnn` which you can run in a debugger. The generated python files are located at `bazel-bin/tasks/dataflow/train_ggnn.runfiles`. You could even copy the files from that runfiles directory back into the tree if you wanted.

Cheers,
Chris

**Comment by wanyao1992** [comment]
Thank you so much for your kind suggestions @ChrisCummins. I will try this way.

Thanks.
