### ISSUE TITLE
Build bug about anaconda x86_64-conda_cos6-linux-gnu-cc

### ISSUE THREAD

**Issue by mengyuan-Sharon** [ChrisCummins/ProGraML#154]
Hello, Author. Thank you very much for your work. It is very enlightening to me. 
When I try to reproduce your code, when building commands tool, run bazel run -c opt //:install - ~/.local/ The following errors will always appear in opt/programl. Could you please help me to find out the reasons? Many thanks！
## To Reproduce

1. Install bazel by npm install -g @bazel/bazelisk and programl-0.1.0 in ~/.local/opt
2.pip install all  requirement.txt 
3. run  bazel run -c opt //:install -- ~/.local/opt/programl
my gcc version on linux is inconsistent with conda gcc，so I  wonder if it is the sourc of bug.
my error is shown below.

error:

ERROR:～/reproduce_ProGraML/bin/BUILD:53:10: Couldn't build file bin/_objs/clang2graph-10/clang2graph.o: C++ compilation of rule '//bin:clang2graph-10' failed (Exit 1) x86_64-conda_cos6-linux-gnu-cc failed: error executing command /anaconda/envs/py37_pytorch/bin/x86_64-conda_cos6-linux-gnu-cc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 ... (remaining 280 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/fmt/src/format.cc:8:0:
bazel-out/k8-opt/bin/external/fmt/_virtual_includes/fmt/fmt/format-inl.h: In function 'void fmt::v6::internal::report_error(fmt::v6::internal::format_func, int, fmt::v6::string_view)':
bazel-out/k8-opt/bin/external/fmt/_virtual_includes/fmt/fmt/format-inl.h:185:3: error: ignoring return value of 'size_t fwrite(const void*, size_t, size_t, FILE*)', declared with attribute warn_unused_result [-Werror=unused-result]
   (void)std::fwrite(full_message.data(), full_message.size(), 1, stderr);

## Environment

- ProGraML version (if building from source, use `git rev-parse HEAD`):
- How you installed ProGraML (source, pip):
- OS:
- Python version:
- Build command you used (if building from source):
- GCC/clang version (if building from source):
- Bazel version (if building from source):
- Versions of any other relevant libraries:

**Comment by ChrisCummins** [comment]
Hi @mengyuan-Sharon, thanks for reporting! That is indeed an error in the build configuration. I've fixed it in 06e925610aa6e371be54101c6bea1ea4bfb99725, you can pull the latest `development` to get the fix.

Cheers,
Chris

**Comment by mengyuan-Sharon** [comment]
thanks a lot！ I reinstalled the tensorflow-gpu and rdflib module on python3.7, and  it works for the error.  It is because the  tensorflow-gpu  module and rdflib failed to be installed.  many thanks again!

**Comment by ChrisCummins** [comment]
Glad to hear!
