### ISSUE TITLE
Source code files for the DeepDataFlow dataset

### ISSUE THREAD

**Issue by sniarchos** [ChrisCummins/ProGraML#156]
Why aren't the source code files of the DeepDataFlow dataset included? Is there any particular reason why you have included the IR files only, without the respective source code files? If not, would it be possible to include them? I need them in order to run some experiments with the ProGraML pipeline while also extracting some static features specifically from the OpenCL source code files. In general, I believe that including the source code files along with the IR files in your dataset would be very helpful for many researchers.

**Comment by ChrisCummins** [comment]
> In general, I believe that including the source code files along with the IR files in your dataset would be very helpful for many researchers.

I agree, and I do regret not uploading the sources. There wasn't any particular need for omitting them, they just weren't relevant for the IR-level experiments I wanted to do.

If you are only interested in the OpenCL files, then you can download the [Device Mapping Dataset](https://www.dropbox.com/s/56epzgyaa5x7eml/devmap_2020.06.27.tar.bz2?dl=1) as that includes the OpenCL sources as well as the LLVM-IR and ProGraML graphs.

Hope that helps.

Cheers,
Chris

**Comment by sniarchos** [comment]
Thank you very much, this really helps a lot!

One last question: I am having a hard time figuring out how to train your system and produce new predictions (and accuracy scores) for my own machine (with my own CPU/GPU pair and my own labels after some experiments on the devmap dataset that you provided). I wonder if you could give me some guidelines regarding this, as I haven't found anything in the documentation?

(I'm really sorry if this is simple/straightforward and it is just a result of my unfamiliarity with `bazel`...)

Thanks again in advance!

**Comment by ChrisCummins** [comment]
Glad that helps.

We never finished open-sourcing the code for graph-level classifications with ProGraML. We got pretty close but then both of the core developers got new jobs and now struggle to find the time to commit to finish it off :) Our most recent work-in-progress is here: https://github.com/ChrisCummins/ProGraML/pull/107

Easiest way to produce new results might be to use an off-the-shelf GGNN implementation from a library like DGL.

Cheers,
Chris
