### ISSUE TITLE
Device Mapping and Algorithm Classification Dataset

### ISSUE THREAD

**Issue by anon767** [ChrisCummins/ProGraML#157]
## 📚 Documentation

Hi!

Would it be possible to include the Device Mapping and Algorithm Classification dataset? I.e. the IR Statements and the corresponding ProGraML graph?

I couldn't find them in the Docs.

Thanks in advance

**Comment by ChrisCummins** [comment]
Hi there, sure! I wanted to get the code ported and merged before releasing the datasets, but it has been several months and I haven't found the time, so here are the datasets:

## Device Mapping

[Dataset Download](https://www.dropbox.com/s/56epzgyaa5x7eml/devmap_2020.06.27.tar.bz2?dl=1)

The `graphs_{amd,nvidia}` directories contain the graphs. The graph-level feature `devmap_label` is `1` if the optimal device is GPU, else `0` if the optimal device is CPU. E.g.:

```
$ pbq --stdin_fmt=pb ProgramGraph < devmap/graphs_amd/amd-app-sdk-3.0-BinomialOption-binomial_options-default.ProgramGraph.pb
...
features {
  feature {
    key: "devmap_label"
    value {
      int64_list {
        value: 1
      }
    }
  }
  ...
}
```

## Algorithm Classification

[Dataset Download](https://www.dropbox.com/s/0vkdesjqnspu17p/classifyapp_2020.05.06.tar.bz2?dl=1)

Again, there is a graph-level feature "poj104_label" with the algorithm class:

```
$ pbq --stdin_fmt=pb ProgramGraph < classifyapp/graphs/99.47990.2.ProgramGraph.pb
...
features {
  feature {
    key: "poj104_label"
    value {
      int64_list {
        value: 99
      }
    }
  }
}
```

**Comment by vrjmath** [comment]
I saw the links say the datasets are deleted. I was wondering if you could revive the dataset link for Device Mapping and Algorithm Classification? Thanks!

**Comment by ChrisCummins** [comment]
Hi @vrjmath, I believe you can find the datasets you're after on Zenodo: https://zenodo.org/records/4247595
