### ISSUE TITLE
Missing the model and training code in the current code in development branch?

### ISSUE THREAD

**Issue by leiyucs** [ChrisCummins/ProGraML#176]
## ❓ Questions and Help
Hi,  I did not find the code of model building and training and the inference code for tasks.   It seems the code is only about data processing and graph construction.    Could you point me to where they are?  Thanks!

**Comment by ChrisCummins** [comment]
Hi @yuleihit, thanks for the question and I'm sorry for the slow response.

You're right, this repo currently only contains graph construction / manipulation code, not the learning scripts. I removed them after the v0.2.0 release to focus on a small and stable API for graph construction. You can find the old training and evaluation code for the dataflow experiments in an older revision:

https://github.com/ChrisCummins/ProGraML/tree/a8fff63f0763e908b233dafdbc0ff9182e7a895a/tasks

I'm working on a much simpler implementation , along with the graph-classification code for algo classification and device mapping, that'll be merged in the future. I created #178 to track progress on this, feel free to follow along there.

Cheers,
Chris
