### ISSUE TITLE
Relax protobuf version requirement

### ISSUE THREAD

**Issue by mihaic** [ChrisCummins/ProGraML#180]
It would be easier install ProGraML together with other packages that depend on protobuf without the current strict version requirement. For example, [Ray](https://pypi.org/project/ray) currently requires `protobuf >= 3.15.3`.

**Comment by ChrisCummins** [comment]
This is a good idea, thanks for the suggestion @mihaic. I'll do this and then make a micro version bump 0.3.1.

Cheers,
Chris

**Comment by mihaic** [comment]
Thanks a lot for the quick fix. Looking forward to the release.

I also opened a related issue (#184), which maybe I could have included here.

**Comment by ChrisCummins** [comment]
No problem, thanks for the suggestions. I created release `programl==0.3.1` with these relaxed dependency versions.
