### ISSUE TITLE
Demo for pretrained checkpoint

### ISSUE THREAD

**Issue by jl63** [ChrisCummins/ProGraML#197]
Hi, great repository! I know that the learning part is still under construction but I am just wondering can I use the existing codes to do a demo for the pretrained model? I am confused by what dataset should I download, how to use the pretrained checkpoint and how to do the evaluation (which file should I run). Thanks a lot!

**Comment by ChrisCummins** [comment]
Hi @jl63, please see [this comment](https://github.com/ChrisCummins/ProGraML/issues/178#issuecomment-950781140) which contains a pointer to an older revision of the code that can run the pretrained checkpoints.

Cheers,
Chris
