### ISSUE TITLE
Graph visualization from my self-define .json/.gexf file

### ISSUE THREAD

**Issue by cheukwaylee** [ChrisCummins/ProGraML#200]
## 🚀 Feature
open source the Graph visualization ( the step from JSON to visually graph as [Program Explorer](https://chriscummins.pythonanywhere.com/))

## Motivation
I need to do some modifications based on your produced graph (to retrieve some lost pragma info as GNN-DSE do), and after that, I have to inspect if it suits my expectations. So I really need a Graph visualization, to make my graph readable.

## Pitch
use .json/.gexf file as input then get a visual graph (of course, I follow ur attributes convention)

## Alternatives
In [Program Explorer](https://chriscummins.pythonanywhere.com/), the c/c++ code can be accepted as input, and if also a JSON file, it would be great!!

**Comment by ChrisCummins** [comment]
Hey @cheukwaylee, very sorry for the slow response, I was on vacation.

The code for program explorer is open source [here](https://github.com/ChrisCummins/program_explorer)! It's in a standalone repo for deploying on python anywhere. Feel free to hack on it and submit a PR, which I can then merge into the upstream version.

Note the actual conversion from C -> graph is done by just running the relevant "X2graph" binary from [here](https://github.com/ChrisCummins/ProGraML/tree/development/programl/bin), see [code pointer](https://github.com/ChrisCummins/program_explorer/blob/master/app/api.py#L41-L53).

Hope that helps!

Chris

**Comment by cheukwaylee** [comment]
@ChrisCummins thank you so much for your kind feedback!! I will have a look at the code you mentioned.

**Comment by cheukwaylee** [comment]
Hi @ChrisCummins, I noticed that the online graph visulization tool [chriscummins.cc/s/program_explorer/](https://chriscummins.cc/s/program_explorer/) is down, so I am trying to use the repo [
program_explorer](https://github.com/ChrisCummins/program_explorer) you told me before, but unfortunately it does not work... May I ask will you plan to fix the online tool?

**Comment by cheukwaylee** [comment]
issue solved, THX!

**Comment by ChrisCummins** [comment]
> Hi @ChrisCummins, I noticed that the online graph visulization tool [chriscummins.cc/s/program_explorer/](https://chriscummins.cc/s/program_explorer/) is down

Yeah I must have forgot to hit the auto-renew button on Python Anywhere.

Could you share what you did to get program explorer to work so that I can add this to the documentation?

Cheers,
Chris
