### ISSUE TITLE
GraphCreationError when using libstdc++.so.6 without GLIBC_2.27, GLIBCXX_3.4.20, and GLIBCXX_3.4.21

### ISSUE THREAD

**Issue by bbartoldson** [ChrisCummins/ProGraML#201]
## 🐛 Bug

The following example (from the README) produces a ```GraphCreationError``` when `libstdc++.so.6` does not have `GLIBC_2.27`, `GLIBCXX_3.4.20`, and `GLIBCXX_3.4.21`.

## To Reproduce

```
import programl as pg
G = pg.from_cpp("""
  #include <iostream>
   int main(int argc, char** argv) {
     std::cout << "Hello, world!" << std::endl;
     return 0;
   }
   """)
```

The specific errors have the form: 

```GraphCreationError: path-to-site-packages/programl/bin/llvm2graph-10: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by path-to-site-packages/programl/bin/llvm2graph-10)```

## Expected behavior

The code runs without errors.

## Environment

- ProGraML version 0.3.2
- Installed via pip
- OS RHEL 7.9
- Python 3.9

## Additional context

The output of `strings /lib64/libstdc++.so.6 | grep GLIBC` is: 
```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBC_2.3
GLIBC_2.2.5
GLIBC_2.14
GLIBC_2.4
GLIBC_2.3.2
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by ChrisCummins** [comment]
Hi @bbartoldson. Thanks for the detailed bug report. Unfortunately I don't have the bandwidth to support binary releases for Red Hat. You could try [building from source](https://github.com/ChrisCummins/ProGraML/blob/development/INSTALL.md#building-from-source), though again, it isn't officially supported.

Another option would be to use one of the python docker images as your base Python version to install ProGraML to.

Cheers,
Chris
