### ISSUE TITLE
Reproduce ICML '21 experiments

### ISSUE THREAD

**Issue by akash-isu** [ChrisCummins/ProGraML#202]
Hi,

I want to reproduce the experiments in the ICML paper (specifically the Device Mapping task). I am doing a study on the performance of various code representations on this task and would be really helpful if I could reproduce it.

Is there a ready-to-use setup of that experiment anywhere?
Apologies if it's already there in the repo, and I was too stupid to find it.

**Comment by ChrisCummins** [comment]
Hi @akash-isu, the input/output datasets for the experiments are available online. Unfortunately the code to repro the experiments is old and hasn't been ported to the latest version of ProGraML yet. Please see [this comment](https://github.com/ChrisCummins/ProGraML/issues/178#issuecomment-950781140) for further details.

Cheers,
Chris

**Comment by akash-isu** [comment]
Hi Chris,

Thank you for your prompt response. I appreciate you pointing me to the right place.
However, I was looking more for the Device Mapping experiments. I know where to get the dataset. I was looking more for the model you implemented for the paper and would like to replicate the exact model. If you had any pointers to where I could find that, it'd be really helpful.

Thank you for your response and help.

Akash

**Comment by ChrisCummins** [comment]
Hi Akash, ah I see, I didn't realize that the older commit doesn't have the code for graph classification checked in! That's a shame. Hmm.

> I was looking more for the model you implemented for the paper and would like to replicate the exact model. If you had any pointers to where I could find that, it'd be really helpful.

We used the same GGNN implementation for both node classification and graph classification. You could start by adapting the existing node classification code to graph classification by changing the way you construct the GGNN. For device mapping, `graph_y_dimensionality=2` and `node_y_dimensionality=0`, for algorithmic classification `graph_y_dimensionality=104` and `node_y_dimensionality=0`:

https://github.com/ChrisCummins/ProGraML/blob/a8fff63f0763e908b233dafdbc0ff9182e7a895a/models/ggnn/ggnn.py#L195-L207

Hope that helps.

Cheers,
Chris
