### ISSUE TITLE
Metadata difference between original LLVM file and produced Graph

### ISSUE THREAD

**Issue by cheukwaylee** [ChrisCummins/ProGraML#203]
## ❓ Questions and Help

Hi @ChrisCummins,

Recently I have been trying to convert the llvm file into graph by calling ProGraML Python API **programl.from_llvm_ir()**. In our case, we are also interested in the feature “bitwidth” of LLVM instruction. As far as I can see, the nodes' attribute **features/full_text** shows the whole LLVM instruction. But unfortunately, this attribute in the produced graph is different from the original LLVM instruction, mainly their metadata is different. 

I guess the possible reason may be that when converting the llvm file to graph, the ProGraML reorganizes all the metadata, but where can I get this info to align them?

THANKS in advance for any help.

**Comment by cheukwaylee** [comment]
An example to make it more clear: the corresponding part in **.ll** and **.gexf** file respectively, but the bitwidth is different

#### in the original LLVM
```llvm
  %empty = alloca i32, !bitwidth !257
  %k = alloca i7, !bitwidth !189
  %j = alloca i6, !bitwidth !190
```
#### in the produced graph
```xml
      <node id="1216" label="1216">
        <attvalues>
          <attvalue for="0" value="4" />
          <attvalue for="4" value="{'full_text': ['%empty = alloca i32, !bitwidth !189']}" />
          <attvalue for="1" value="3" />
          <attvalue for="2" value="alloca" />
          <attvalue for="3" value="0" />
        </attvalues>
      </node>
      <node id="1217" label="1217">
        <attvalues>
          <attvalue for="0" value="4" />
          <attvalue for="4" value="{'full_text': ['%k = alloca i7, !bitwidth !190']}" />
          <attvalue for="1" value="3" />
          <attvalue for="2" value="alloca" />
          <attvalue for="3" value="0" />
        </attvalues>
      </node>
      <node id="1218" label="1218">
        <attvalues>
          <attvalue for="0" value="4" />
          <attvalue for="4" value="{'full_text': ['%j = alloca i6, !bitwidth !191']}" />
          <attvalue for="1" value="3" />
          <attvalue for="2" value="alloca" />
          <attvalue for="3" value="0" />
        </attvalues>
      </node>
```

**Comment by ChrisCummins** [comment]
Hi @cheukwaylee, sorry for the slow reply.

That's an interesting bug. I believe the bitwidth values (`!257`, `!189`, etc) are references to metadata strings. The numbers themselves are only indexes into a list of strings. My guess is that when ProGraML serializes the text for the instructions, the indices change, causing the values to be lost. You may want to consider directly embedding the value for those bitwidths in the full_text, rather than the index. Here's a couple of code pointers:

This is where nodes are constructed from functions, including setting `full_text`:

https://github.com/ChrisCummins/ProGraML/blob/cd7d2939d485d989a9b105723fed989bcaca1f94/programl/ir/llvm/internal/program_graph_builder.cc#L300-L322

This is the logic for serializing an instruction into the `full_text` representation:

https://github.com/ChrisCummins/ProGraML/blob/cd7d2939d485d989a9b105723fed989bcaca1f94/programl/ir/llvm/internal/text_encoder.cc#L99-L129

Let me know if that helps.

Cheers,
Chris

**Comment by cheukwaylee** [comment]
Hi @ChrisCummins, many thanks for your kind feedback, it helps me a lot!! At least for now I can do some modifications at ProGraML and re-compile it.

You remind me that something like `!257` is nothing but a reference to the Metadata node. And we suppose the `!bitwidth !257` describes how complex the llvm instruction is, so it should be considered as node's feature. 

What we want is to extract the Metadata info.I got the `MDNode` by using the following function with filter argument `"bitwidth"`. But unfortunately, I don't know how to convert it to a simple string and then pass it to ProGraML (as nodes' attribute).
```C++
::llvm::MDNode* MDN = instruction->getMetadata("bitwidth");
```

After referring to the blog [http://blog.llvm.org/2010/04/extensible-metadata-in-llvm-ir.html](url), I know that `MDNode` is a tuple that can reference arbitrary LLVM IR values in the program as well as other metadata, so it should be extracted recursively. Each `MDNode` can have many operands. The draft code as follows, but it doesn't work :(
```C++
int numOperand = MDN->getNumOperands();
for (size_t i = 0; i < numOperand; i++) {
  const ::llvm::MDOperand& MDOpRef = MDN->getOperand(i);
  ::llvm::MDString* MDStr = ::llvm::cast<::llvm::MDString>(MDOpRef);
  ::llvm::StringRef StrRef = MDStr->getString();

  encoded.bitwidthAttr += StrRef.str(); // add to ProGraML
}
```

Moreover, I found a repo [https://github.com/madhur13490/LLVM-Metadata-Visualizer](url) for visualizing the Metadata as an undirected graph to show its internal reference relationship. But this repo seems to be implemented through text analysis. I believe it would be better if it can be extracted through LLVM lib interface.

Once I can figure out the reference relationship of every Metadata, and then it can be converted to a string and pass it to the ProGraML and eventually as the node's feature.

Any suggestion will be highly appreciated!!!

**Comment by ChrisCummins** [comment]
> What we want is to extract the Metadata info.I got the `MDNode` by using the following function with filter argument `"bitwidth"`. But unfortunately, I don't know how to convert it to a simple string and then pass it to ProGraML (as nodes' attribute).

That sounds like a good plan. I can't help you with the MDNode to string conversion (may be worth asking on the LLVM discourse), but once you have the string, you could add to the ProGraML graph as a node feature:

```c++
Node* ProgramGraphBuilder::AddLlvmInstruction(const ::llvm::Instruction* instruction,
                                              const Function* function) {
  Node* node = AddInstruction(text.opcode_name, function);
  // ...
  const std::string bitwidthAsString = /* implement this bit */
  graph::AddScalarFeature(node, "bitwidth", bitwidthAsString);
  // ...
}
```

Cheers,
Chris

**Comment by cheukwaylee** [comment]
THANKS for your kind answer! I will have a look at LLVM things.

Merry Christmas and happy New Year!
Zhuowei
