### ISSUE TITLE
Error due to DGLHeteroGraph imports

### ISSUE THREAD

**Issue by akash-isu** [ChrisCummins/ProGraML#206]
## To Reproduce

1. pip install dgl (dgl version 1.0.1)
1. python3
1. import programl

With DGL version 1.0.1, the statement "from dgl.heterograph import DGLHeteroGraph" throws an error as the DGLHeteroGraph no longer exists in dgl.heterograph in the latest version of dgl.
Verified that this error does not occur with 0.6.2 and 0.9.0.

- ProGraML version (if building from source, use `git rev-parse HEAD`): 0.3.2
- How you installed ProGraML (source, pip): pip
- OS: Ubuntu 20.04, Mac
- Python version: 3.9.*, 3.10.*
- Build command you used (if building from source):
- GCC/clang version (if building from source):
- Bazel version (if building from source):
- Versions of any other relevant libraries:

Suggestion: Maybe having a disclaimer in the Readme would work for now.

**Comment by volpepe** [comment]
+1, had the same problem today because 1.0.1 is installed automatically when running `pip install programl`. OP solution solved it.

**Comment by ChrisCummins** [comment]
Thanks for the report @akash-isu and the confirmation @volpepe! I'll need to tighten up the dgl version requirement, easy patch :)
