### ISSUE TITLE
Missing GNN models

### ISSUE THREAD

**Issue by igabirondo16** [ChrisCummins/ProGraML#209]
## Missing GNN model

Hello Chris, I am currently working with the ProGraML graphs, and I would like to reproduce the experiments described in the paper. 

I have been exploring the repository, and in this [file](https://github.com/ChrisCummins/ProGraML/blob/development/Documentation/ProjectStructure.md) a directory with the models is mentioned. Nevertheless, the link to the directory does not work and I have not found any file with either the GNN architecture or the learnt weights.

Is there any place in which I can find the model files?

Many thanks in advance,

Iñigo.

**Comment by ChrisCummins** [comment]
Thanks for flagging.

For the paper we has some custom ad-hoc GGNN implementation which I never really liked and got overly complex. I have long had an item on my todo list to replace it with something simple like pytorch geometric but have zero bandwidth to work on it :(

You're welcome to dig through the repo archive if you'd prefer to use our GGN implementation: https://github.com/ChrisCummins/ProGraML/issues/178#issuecomment-950781140

Cheers,
Chris
