### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by PingChang818** [ChrisCummins/ProGraML#210]
## ❓ Questions and Help

Hello Chris,

When I run "pip install programl", the error message shows:

ERROR: Could not find a version that satisfies the requirement programl (from versions: none)
ERROR: No matching distribution found for programl

Could you please help? My Python version is 3.9.16. Thanks in advance!

**Comment by PingChang818** [comment]
Only available on Linux.

**Comment by ChrisCummins** [comment]
Linux and Intel macOS. What OS are you interested in?
