### ISSUE TITLE
How to train a GNN model?

### ISSUE THREAD

**Issue by Panhaolin2001** [ChrisCummins/ProGraML#215]
## ❓ Questions and Help

```
import programl as pg
# Construct a program graph from C++:
G = pg.from_cpp("""
... #include <iostream>
...
... int main(int argc, char** argv) {
...   std::cout << "Hello, world!" << std::endl;
...   return 0;
... }
... )

# Convert the graph to NetworkX:
graph = pg.to_networkx(G)
```

Once I have networkx type data, how do I train a custom gnn model? How to extract features from graph variables for training? My job is to train at the graph level. Is there still one more step to encode inst2vec into it? Look forward to your answer, thank you!

**Comment by ChrisCummins** [comment]
The result of `pg.to_networkx()` includes the node / edge features already, check the data dict for each. We don't have model training code in this repo, but you can find examples of GNN training from networkx and adapt them to your dataset of ProGraML graphs. Hope that helps!

Chris

**Comment by Panhaolin2001** [comment]
> The result of `pg.to_networkx()` includes the node / edge features already, check the data dict for each. We don't have model training code in this repo, but you can find examples of GNN training from networkx and adapt them to your dataset of ProGraML graphs. Hope that helps!
> 
> Chris

Thank you, but I see that the node and edge features in networkx are text type; I want to do a graph-level supervised learning task. Now I have a lot of llvm ir codes, and each llvm ir code has a label. My first step is to convert all llvm ir codes into program graph, and then into networkx. What should we do next?
Or is there a complete step from llvm ir to the final predicted successful code demo? Thank you!

**Comment by ChrisCummins** [comment]
> What should we do next?

That depends on what you're trying to do :-) You can encode those text features into whatever representation you like. If your goal is to use inst2vec embeddings for nodes, then there is an inst2vec API built in, or a command line tool: https://github.com/ChrisCummins/ProGraML/blob/development/Documentation/bin/inst2vec.txt
