### ISSUE TITLE
/usr/bin/python3 not found on mac os

### ISSUE THREAD

**Issue by Zacharias030** [ChrisCummins/ProGraML#51]
If `/usr/bin/python3` doesn't exist, as it probably shouldn't on mac os (10.14.3), this fails:
`bazel run //deeplearning/ml4pl/graphs/unlabelled/llvm2graph -- < /tmp/foo.ll`.

Error:
```
Target //deeplearning/ml4pl/graphs/unlabelled/llvm2graph:llvm2graph up-to-date:
  bazel-bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph
INFO: Elapsed time: 67,705s, Critical Path: 20,35s
INFO: 189 processes: 189 darwin-sandbox.
INFO: Build completed successfully, 193 total actions
INFO: Build completed successfully, 193 total actions
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_Zacharias/7fe3063fd5d91d7b28baf77dd699e6ca/execroot/phd/bazel-out/darwin-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph", line 349, in <module>
    Main()
  File "/private/var/tmp/_bazel_Zacharias/7fe3063fd5d91d7b28baf77dd699e6ca/execroot/phd/bazel-out/darwin-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph", line 339, in Main
    os.execv(args[0], args)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/python3'
(base) ➜  chris_phd_repo git:(master) bazel --version
bazel 1.2.1-homebrew
```

**Comment by Zacharias030** [comment]
cannot symlink there without disabling SIP.

**Comment by Zacharias030** [comment]
obviously all python stuff is symlinked into `/usr/local/bin`

**Comment by Zacharias030** [comment]
solved it by disabling SIP and linking /usr/local/bin/python3 to /usr/bin/python3. But that is not good for other people.

**Comment by ChrisCummins** [comment]
Yep I agree. What's weird is that my mac has `/usr/bin/python3` (not a brew symlink). Either way, bazel should have no problem finding the appropriate python3 version

**Comment by ChrisCummins** [comment]
Closing this as it's a general "gotcha" with bazel that should be addressed upstream. For now, I've added an entry to the build docs which might help in debugging this:

https://github.com/ChrisCummins/phd/blob/master/INSTALL.md#non-standard-path
