### ISSUE TITLE
Improving LLVM node representations

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisCummins/ProGraML#55]
This issue tracks changes to the `preprocessed_text` and `x` fields of nodes produced by `llvm2graph`. This will be a breaking change for the old inst2vec-based node encoder.

**Comment by ChrisCummins** [comment]
I've modified the llvm2graph implementation to be backward compatible with the old graph representation by inserting `#ifdef PROGRAML_FUTURE_NODE_REPRESENTATION` guards around changes to the representation.

**Comment by ChrisCummins** [comment]
PR to reset llvm2graph output to the "old" format: github.com/ChrisCummins/phd/pull/95

**Comment by Zacharias030** [comment]
I'm strongly in favor of working on this issue, though for now I plan to base experimental results on the PR 95 (github.com/ChrisCummins/phd/pull/95). In any case it will be interesting to have carefully produced results under the old node tokenization to compare against for isolating the benefits of any changes.

**Comment by ChrisCummins** [comment]
Merging @Zacharias030 's bug report from #59:

> [Current inst2vec] has problems with whitespace, somehow not reducing the consecutive spaces on this node:
```
node_data={'type': 0, 'text': 'switch i32 %18, label %78 [\n    i32 1, label %19\n    i32 2, label %60\n  ], !dbg !498, !prof !499', 'preprocessed_text': 'switch i32 <%ID>, label <%ID> [\n    i32 <INT>, label <%ID>\n    i32 <INT>, label <%ID>\n  ]', 'function': 'check_refine', 'x': [8564], 'y': [], 'llvm_profile_total_weight': 4925879498}
```

**Comment by ChrisCummins** [comment]
Fixed in the alpha implementation.
