### ISSUE TITLE
Extending to XLA IR

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisCummins/ProGraML#56]
This is a tracking issue for adding the ability to generate ProGraML graphs for use in graph machine learning experiments from XLA HLO Modules.

[XLA](https://www.tensorflow.org/xla) is an optimizing compiler for machine learning with frontends for TensorFlow, JAX, and PyTorch. XLA has two IRs covering "High" and "Low" level representations, named HLO and LLO, respectively. This patchset adds the ability to construct ProgramGraphs from HLO IR.

HLO has a very different design to LLVM IR. A HLO module is structured as a data flow graph, where instructions each have one or more operands. Instructions are composed into computations, which in turn are composed into modules. Although HLO provides the ability to specify control dependencies between instructions, I have not actually seen this used in practice. Instead, an instruction order can be inferred from the data flow graph.

## Status

- [x] Initial implementation of HloProto -> ProgramGraphProto (github.com/ChrisCummins/phd/pull/98).
- [ ] Refine and finalize graph representation.
- [ ] Collect a dataset of HloProtos.
- [ ] Generate labeled program graphs using some interesting analysis / optimization problem.

## Design

My approach for constructing ProGraML graphs from HLO has been to closely follow the pattern used for LLVM. Specifically:

1. A HloComputation is treated as a function.
1. Each HloComputation begins with a dummy 'computation entry' instruction, which acts as the root for control dependencies into the computations instructions.
1. Each instruction produces an identifier node, parameterised by the instruction's shape.
1. Data flow edges connect producer instructions to consumers.
1. Call edges connect instructions to the entry and exit instructions of the called HloComputations.
1. The control dependency between producer and consumer instructions is made explicit through the addition of control edges. A difference between this and LLVM which needs consideration is that this produces parallel control edges, whereby an instruction with multiple consumers has multiple control out edges. In LLVM, these multiple control edges would only occur as a result of branch / switch statements, and only a single path is walked. With HLO, all control branches will be executed. For the data flow experiments we have considered so far, this change does not matter, but we may want to discuss and revise this.

This is the program graph generated from example HloModule for a simple TensorFlow linear regressor:

![dot](https://user-images.githubusercontent.com/1636663/74108419-29ed6480-4b72-11ea-871f-d71fbd8a94df.png)

## Usage

The new //deeplearning/ml4pl/graphs/xla2graph package contains a graph
constructor, implemented in C++, which reads a HloProto message from
stdin and writes a generated ProgramGraph message to stdout. You can
generate HloProto messages from TensorFlow by running your TensorFlow
app with XLA enabled and the debugging --dump_hlo_as_proto flag
enabled:

```sh
$ TF_XLA_FLAGS=--tf_xla_auto_jit=2 \
   XLA_FLAGS="--xla_dump_hlo_as_proto --xla_dump_to=/tmp/hlo"
   path/to/your/tf/program
```

Then generate a graph using:

```sh
$ bazel run //deeplearning/ml4pl/xla2graph --  /tmp/hlo/module.hlo.pb
```

I have also provided python bindings to generate protocol buffers or networkx graphs, available using:

```py
from deeplearning.ml4pl.graphs.xla2graph.py import xla2graph

graph = xla2graph.BuildProgramGraphProto(proto)
nx_graph = xla2graph.BuildProgramGraphNetworkx(proto)
```

**Comment by Zacharias030** [comment]
crazy stuff!
The call edge going back look somewhat strange in the way that the last computation assigns to an identifier which is dangling and not used in the computation of the callee. What’s going on?
Am 13. Feb. 2020, 22:53 +0100 schrieb Chris Cummins <notifications@github.com>:

**Comment by ChrisCummins** [comment]
This is to match the representation we use for LLVM, which doesn't track data edges across function boundaries. Only call edges cross the function boundary. For XLA, given that we have a nice clear data flow graph, this looks a bit silly, but is consistent with LLVM. Maybe, in both cases, there would be a case for adding the data edges ...

**Comment by ChrisCummins** [comment]
What is harder to remain consistent with LLVM is the parallel control edges. In LLVM, a node with multiple outgoing control edges is a branch, and only a single path will be taken. With XLA, *all* paths will be taken, since the control edge simply makes the implicit control dependency explicit. Currently I use the same positional embedding for outgoing control edges, but this seems misleading in the context of XLA. 

There is a good case to be made for omitting the entire CFG from the XLA representation (since it doesn't have one), but again, I made one for consistency with LLVM.

**Comment by ChrisCummins** [comment]
Graph construction from XLA is done, closing.
