### ISSUE TITLE
benchmark dataset of 250k LLVM-IR

### ISSUE THREAD

**Issue by monperrus** [ChrisCummins/ProGraML#61]
Hello Chris,

Would you have a version of the benchmark dataset of 250k LLVM-IR mentioned in your paper? for instance on Zenodo?

Thanks!

--Martin

**Comment by ChrisCummins** [comment]
Hi Martin,

Absolutely! We're still figuring out the best way to share our datasets at the moment, but if you drop me an email at chrisc.101@gmail.com I can just zip up the IR files as a one-off for you.

Cheers,
Chris

**Comment by ChrisCummins** [comment]
Dataset delivered :)

**Comment by monperrus** [comment]
Thanks Chris for sharing the dataset over email!

**Comment by ChrisCummins** [comment]
Update: The dataset is [now live](https://github.com/ChrisCummins/ProGraML/blob/master/programl/Documentation/DataflowDataset.md)!

**Comment by monperrus** [comment]
Excellent, thanks a lot!

For long-term preservation of scientific data, Zenodo seems better than Dropbox.

**Comment by ChrisCummins** [comment]
I agree. Once we've ironed out a few more details we'll be uploading it there.

Cheers,
Chris
