### ISSUE TITLE
Generating sequences for DeepTune_IR

### ISSUE THREAD

**Issue by zjq7** [ChrisCummins/ProGraML#62]
In Setup  of  README.md , "See INSTALL.md. Build and run the test suite using", but I cannot find file INSTALL.md, thanks.

**Comment by ChrisCummins** [comment]
Hi @zjq7, apologies! We are currently working on quite a big rewrite of the code and will have an update pushed by the end of next week. I'll ping you here when it's live!

**Comment by zjq7** [comment]
thanks for your reply,  Can you tell me about How to generate sequences to finish deeptuneir experiment, and is the method used inst2vec or clgen? I want to train Deeptune with IR generation sequence, but I don't know where your code is, so I hope you can give me some tips, thanks.

**Comment by ChrisCummins** [comment]
Hi @zjq7, sorry it took a while to get back to you. Regarding your first question, the INSTALL.md file has been restored.

There are two methods to extend DeepTune to LLVM-IR:

### Using tokenized LLVM-IR

![deeptune_ir](https://user-images.githubusercontent.com/1636663/83934263-93d7ec80-a7a7-11ea-886b-ab3924e5b5b5.png)

The first is using the `DeepTune_IR` method from [this paper](https://arxiv.org/abs/2003.10536). It uses the same tokenization approach in [DeepTune](https://chriscummins.cc/pub/2017-pact.pdf), but using a vocabulary derived from LLVM.

The vocab can be found here:
https://github.com/ChrisCummins/phd/blob/da67673ecce9bcf30fbabd7af849ebb614ef951b/deeplearning/ml4pl/seq/llvm_vocab.json

The code for turning an LLVM-IR into a sequence of vocabulary elements is here:
https://github.com/ChrisCummins/phd/blob/da67673ecce9bcf30fbabd7af849ebb614ef951b/deeplearning/ml4pl/seq/cached_string_encoder.cc#L34-L94

And the batch construction for an LSTM is here:
https://github.com/ChrisCummins/phd/blob/da67673ecce9bcf30fbabd7af849ebb614ef951b/deeplearning/ml4pl/models/lstm/node_lstm.py#L236-L393


### Using inst2vec

![inst2vec](https://user-images.githubusercontent.com/1636663/83934265-963a4680-a7a7-11ea-920f-3dd370cca559.png)

Another approach is to use inst2vec to process each line of LLVM-IR in turn. This produces a simpler model as you don't need the "node groupings" from the model above.

The model is implemented here: https://github.com/ChrisCummins/ProGraML/blob/921892bae54ad8b79258f85c2f7025b4c6d35668/programl/ml/model/lstm/lstm.py#L117-L174

Batch construction is here:
https://github.com/ChrisCummins/ProGraML/blob/921892bae54ad8b79258f85c2f7025b4c6d35668/programl/task/dataflow/lstm_batch_builder.py#L83-L114

Hope that helps!

Cheers,
Chris

**Comment by ChrisCummins** [comment]
Closing this as it is a question not an issue, but feel free to comment if you have any further questions!
