### ISSUE TITLE
errors when running the script for generating the Devmap dataset and the classifyapp dataset

### ISSUE THREAD

**Issue by Jeansma** [ChrisCummins/ProGraML#74]
Hi, 
I met the below errors when building the "programl/task/devmap/dataset: create" for generating the devmap dataset, and the same errors happened when generating the classifyapp dataset too: 

ERROR: /home/guixiang/.cache/bazel/_bazel_guixiang/dd912385bee95efb93050c700b90173d/external/com_github_chriscummins_rules_bats/bats.bzl:39:11: name 'DefaultInfo' is not defined.
ERROR: Skipping 'programl/task/classifyapp/dataset:create': error loading package '': Extension 'bats.bzl' has errors.
WARNING: Target pattern parsing failed. Continuing anyway.
ERROR: Failed to load //external package: error loading package '': Extension 'bats.bzl' has errors.

Do you have any idea on how to fix these? Or if possible, could you share the graph data you've generated for devmap and classifyapp? Thanks a lot!!

**Comment by ChrisCummins** [comment]
Hi @Jeansma,

Thanks for reporting. It looks like there's an error in pulling in the [rules_bats](https://github.com/ChrisCummins/rules_bats) dependency. Is that the entire output? Would you mind posting the full build output, including the command you ran, and the version of bazel that you are using?

The devmap and classifyapp datasets are currently being verified (we recently rewrote a large part of the codebase and want to make sure everything is tip top before releasing it publicly). Of course, if you are in a hurry, feel free to drop me an email at chrisc.101@gmail.com and I can send you a sneak peek. :)

Cheers,
Chris

**Comment by Jeansma** [comment]
Hi @ChrisCummins ,

Thanks a lot for your response. Below is the command I ran and the entire output, and I am using bazel version 0.4.5. 

bash-4.2$ bazel build programl/task/classifyapp/dataset:create 
      
Warning: ignoring http_proxy in environment.
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: /home/guixiang/.cache/bazel/_bazel_guixiang/dd912385bee95efb93050c700b90173d/external/com_github_chriscummins_rules_bats/bats.bzl:39:11: name 'DefaultInfo' is not defined.
ERROR: Skipping 'programl/task/classifyapp/dataset:create': error loading package '': Extension 'bats.bzl' has errors.
WARNING: Target pattern parsing failed. Continuing anyway.
ERROR: Failed to load //external package: error loading package '': Extension 'bats.bzl' has errors.
INFO: Elapsed time: 0.087s

Before the above errors, I've also met an error "ERROR: /home/guixiang/GSL/ProGraML/tools/bzl/deps.bzl:129:3: //external:com_google_absl: no such attribute 'url' in 'http_archive' rule. " So I fixed the "url" in the "deps.bzl" file, by replacing "url" with "urls", and add a pair of brackets [ ] around the assigned value for the url, so it became a list (to be consistent with the type of other "urls"). 

Thanks for letting me know that you are verifying the devmap and classifyapp datasets. Currently I am eager to run some analysis for the graph-level classification on these two datasets, so it would be great if you could send me a sneak peek of the two datasets. I've also sent you an email about this last Friday(July 31) (My email address is: guixiang.ma@intel.com). If you could share the two datasets with me, that would be great! 

Thanks a lot,
Guixiang

**Comment by ChrisCummins** [comment]
Hi Guixiang,

Thanks for following up! Your version of bazel is unsupported. Unfortunately, there isn't a mechanism in bazel for detecting the version, else it would be possible to provide a better error message. :-)

I would recommend building with [v3.0.0](https://github.com/bazelbuild/bazel/releases/tag/3.0.0), which you can install in a custom prefix so you don't have to replace the system-wide version.

I shared the datasets with you via email, so closing this now! Feel free to re-open/file a new issue if you encounter further build errors.

Cheers,
Chris

**Comment by Jeansma** [comment]
Thanks Chris! I see now. Appreciate your help!! 

Best,
Guixiang
