### ISSUE TITLE
Can it support auto-grad ?

### ISSUE THREAD

**Issue by FDInSky** [ChrisCummins/ProGraML#78]
Can it support auto-grad?

**Comment by Zacharias030** [comment]
Could you elaborate on your question? How would you like to use autograd?
Am 13. Aug. 2020, 05:20 +0200 schrieb FDInSky <notifications@github.com>:

**Comment by FDInSky** [comment]
Recent deep learning frameworks transfer computation graph representation into compiler ir. Could ProgGraML used in this transform process to speed up running ?

**Comment by FDInSky** [comment]
https://github.com/FluxML/Zygote.jl， this lib use SSA IR to generate a graph IR and then do auto differential. Would you like to add this feature ?

**Comment by Zacharias030** [comment]
We would need a research question related to this to incorporate it. What did you have in mind?

In any case, we would be happy to accept pull requests, if you implement a new feature!

**Comment by ChrisCummins** [comment]
HI @FDInSky , thanks for the question, but I'm not quite sure what you're proposing. From what I can tell, Zygote is a source-to-source transpiler which adds automatic differentiation to Julia. Is your question whether we could implement this transpilation using machine learning and ProGraML? Or whether the Julia graphs could be converted to ProGraML? Or something else?

Cheers,
Chris

**Comment by FDInSky** [comment]
I means that adds auto-diff to ProGraML.
