### ISSUE TITLE
Add code for graph-level tasks

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisCummins/ProGraML#81]
The graph-level tasks in the arXiv paper aren't yet ported to the new codebase:

- [ ] Rebase #81 onto new `development` project structure.
- [ ] Verify devmap results.
- [ ] Verify classifyapp results.

**Comment by ChrisCummins** [comment]
After merging #142 the #81 PR will need refreshing. See @Kadakol's investigation in https://github.com/ChrisCummins/ProGraML/issues/144#issuecomment-730864122 for a good list of pending issues.

Cheers,
Chris

**Comment by Kadakol** [comment]
Hi @ChrisCummins. Could you please me know if there are any updates regarding stabilising this branch?

**Comment by ChrisCummins** [comment]
Ach, no sorry :-( I've been super busy with other projects. It's till on my todo list!

Cheers,
Chris

**Comment by Kadakol** [comment]
I understand. Thank you for your quick response!

**Comment by ChrisCummins** [comment]
Superseded by #178.
